#ifndef UNROLLED_LONG_DOUBLE_PTR_INC_H_
#define UNROLLED_LONG_DOUBLE_PTR_INC_H_

/**
>>> 524288/16
32768
>>> 32768/16
2048
>>> 2048/16
128
>>> 128/16
8
>>>
*/

#define UNROLLED_LONG_DOUBLE_PTR_INC_LINE {\
  ptr++;\
}

#define UNROLLED_LONG_DOUBLE_PTR_INC_LINE8 {\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE\
}

#define UNROLLED_LONG_DOUBLE_PTR_INC_LINE128 {\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE8\
}

#define UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048 {\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE128\
}

#define UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768 {\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE2048\
}

#define UNROLLED_LONG_DOUBLE_PTR_INC_LINE524288 {\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
  UNROLLED_LONG_DOUBLE_PTR_INC_LINE32768\
}

#endif
